import { css } from 'jimu-core'

export const getStyle = () => css`
  --insar-ink:#17252a; --insar-muted:#687b80; --insar-line:#dce5e7; --insar-teal:#087f75; --insar-dark:#064f4d; --insar-soft:#e9f6f3;
  width:100%; height:100%; min-height:360px; overflow-y:auto; overflow-x:hidden; overscroll-behavior:contain; color:var(--insar-ink); background:#f7f9f9; font-family:var(--ref-typeface-brand,"Avenir Next",Arial,sans-serif);
  *{box-sizing:border-box} button,input,select{font:inherit}
  .insar-shell{min-height:100%; display:block; min-width:0}
  .insar-header{flex:0 0 auto; padding:17px 18px 14px; color:#fff; background:linear-gradient(135deg,#073f45,#0a7473); position:relative; overflow:hidden}
  .insar-header:after{content:""; position:absolute; width:130px; height:130px; border:25px solid rgba(255,255,255,.06); border-radius:50%; right:-55px; top:-75px}
  .insar-eyebrow{font-size:10px; letter-spacing:.12em; opacity:.76; text-transform:uppercase}.insar-title{margin:3px 0 0; font-size:21px}.insar-source{margin-top:8px; font-size:10px; opacity:.78}
  .insar-filters{flex:0 0 auto; padding:12px 13px; background:#fff; border-bottom:1px solid var(--insar-line)}
  .insar-grid{display:grid; grid-template-columns:1fr 1fr; gap:9px}.insar-field label{display:block; margin:0 0 4px; color:var(--insar-muted); font-size:9px; font-weight:750; letter-spacing:.06em; text-transform:uppercase}
  .insar-field select,.insar-field input{width:100%; height:34px; padding:0 8px; border:1px solid #cbd7da; border-radius:6px; color:var(--insar-ink); background:#fff; min-width:0}
  .insar-field select:focus,.insar-field input:focus{outline:none; border-color:var(--insar-teal); box-shadow:0 0 0 2px rgba(8,127,117,.12)}
  .insar-actions{display:flex; justify-content:space-between; align-items:center; margin-top:9px}.insar-clear{border:0; color:var(--insar-dark); background:transparent; font-size:11px; font-weight:700; cursor:pointer}.insar-count{font-size:10px;color:var(--insar-muted)}
  .insar-tabs{display:grid;grid-template-columns:1fr 1fr;position:sticky;top:0;z-index:4;background:#fff;border-bottom:1px solid var(--insar-line)}.insar-tabs button{height:43px;border:0;border-bottom:3px solid transparent;color:var(--insar-muted);background:#fff;font-size:11px;font-weight:700;cursor:pointer}.insar-tabs button.active{color:var(--insar-dark);border-bottom-color:var(--insar-teal)}.insar-tabs span{display:inline-grid;place-items:center;min-width:18px;height:18px;margin-left:4px;border-radius:9px;background:var(--insar-soft);font-size:9px}
  .insar-content{padding:12px}
  .insar-kpis{display:grid; grid-template-columns:repeat(3,1fr); gap:8px}.insar-kpi{padding:10px; border:1px solid var(--insar-line); border-radius:8px; background:#fff}.insar-kpi span{display:block; color:var(--insar-muted); font-size:9px; text-transform:uppercase}.insar-kpi strong{display:block; margin-top:4px; color:var(--insar-dark); font-size:17px}.insar-kpi small{font-size:9px;color:var(--insar-muted)}
  .insar-panel{margin-top:10px; padding:11px; border:1px solid var(--insar-line); border-radius:8px; background:#fff}.insar-panel-head{display:flex; justify-content:space-between; align-items:center; margin-bottom:8px}.insar-panel h3{margin:0;font-size:12px}.insar-panel-head span{font-size:9px;color:var(--insar-muted)}
  .insar-chart-scroll{width:100%;overflow-x:auto;overflow-y:hidden;padding-bottom:5px}.insar-chart{height:128px;display:block;overflow:visible}.insar-axis{stroke:#d8e2e3;stroke-width:1}.insar-area{fill:rgba(8,127,117,.12)}.insar-line{fill:none;stroke:var(--insar-teal);stroke-width:2}.insar-dot{fill:#fff;stroke:var(--insar-teal);stroke-width:1.5}.insar-dot.is-action{cursor:pointer}.insar-dot.is-action:hover,.insar-dot.is-action:focus{fill:#c20084;stroke:#fff;stroke-width:2;outline:none}
  .insar-empty{height:100%; min-height:240px; display:flex; flex-direction:column; align-items:center; justify-content:center; padding:30px; text-align:center; color:var(--insar-muted)}.insar-empty strong{color:var(--insar-ink);margin-bottom:5px}.insar-spinner{width:25px;height:25px;margin-bottom:12px;border:3px solid #d5e4e3;border-top-color:var(--insar-teal);border-radius:50%;animation:insar-spin .8s linear infinite}@keyframes insar-spin{to{transform:rotate(360deg)}}
  .insar-list{display:grid;gap:6px}.insar-row{width:100%;display:grid;grid-template-columns:minmax(0,1fr) auto;gap:10px;padding:9px;border:1px solid #e1e8e9;border-radius:7px;text-align:left;color:inherit;background:#fff;cursor:pointer}.insar-row:hover{border-color:#8fc6c1;background:#fbfefe}.insar-row strong{display:block;font-size:11px;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.insar-row-meta{margin-top:3px;color:var(--insar-muted);font-size:9px}.insar-value{text-align:right;color:var(--insar-dark);font-size:13px;font-weight:750}.insar-type{display:block;margin-top:2px;font-size:8px;color:var(--insar-muted);font-weight:500}
  .insar-images{background:#f6f8f8}.insar-image-list{padding:8px 10px 12px}.insar-image-card{position:relative;margin:6px 0;border:1px solid transparent;border-radius:9px;background:#fff;box-shadow:0 1px 3px rgba(20,50,55,.08)}.insar-image-card.active{border-color:var(--insar-teal);box-shadow:0 0 0 1px var(--insar-teal)}.insar-image-card.compare{border-color:#9c7b30}.insar-image-select{width:100%;min-height:88px;display:grid;grid-template-columns:48px minmax(0,1fr) 25px;gap:11px;align-items:center;padding:10px 10px 30px;border:0;text-align:left;color:inherit;background:transparent;cursor:pointer}.insar-date-box{width:46px;height:52px;display:flex;flex-direction:column;align-items:center;justify-content:center;border-radius:7px;color:#31565a;background:#edf3f3}.insar-date-box strong{font-size:19px}.insar-date-box small{font-size:9px;text-transform:uppercase}.insar-image-copy{min-width:0}.insar-image-copy strong{display:block;font-size:12px}.insar-image-copy small{display:block;margin-top:5px;color:var(--insar-muted);font-size:9px;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.insar-image-copy em{display:inline-block;margin-top:6px;padding:2px 7px;border-radius:10px;color:var(--insar-dark);background:var(--insar-soft);font-size:8px;font-style:normal;font-weight:750}.insar-check{width:23px;height:23px;display:grid;place-items:center;border:1px solid #cad6d8;border-radius:50%;color:#fff}.active .insar-check{border-color:var(--insar-teal);background:var(--insar-teal)}.compare .insar-check{border-color:#9c7b30;background:#9c7b30}.insar-opacity{position:absolute;right:9px;bottom:7px;height:22px;padding:0 8px;border:1px solid #c7d4d6;border-radius:11px;color:#486168;background:#f7f9f9;font-size:9px;font-weight:700;cursor:pointer}
  .insar-image-footer{padding:11px 14px 14px;border-top:1px solid var(--insar-line);background:#fff}.insar-image-nav{display:grid;grid-template-columns:36px 1fr 36px;gap:8px;align-items:center}.insar-image-nav button{height:35px;border:1px solid #cbd7da;border-radius:7px;color:var(--insar-dark);background:#fff;font-size:20px}.insar-image-nav button:disabled{opacity:.3}.insar-image-nav span{text-align:center;color:var(--insar-muted);font-size:9px}.insar-image-nav strong{display:block;margin-bottom:2px;color:var(--insar-ink);font-size:11px}.insar-compare-row{display:flex;justify-content:space-between;align-items:center;margin-top:10px;padding-top:10px;border-top:1px solid #e5ebec}.insar-compare-row strong,.insar-compare-row small{display:block}.insar-compare-row strong{font-size:11px}.insar-compare-row small{margin-top:2px;color:var(--insar-muted);font-size:9px}.insar-toggle{width:39px;height:22px;padding:2px;border:0;border-radius:12px;background:#bdc9cb}.insar-toggle i{display:block;width:18px;height:18px;border-radius:50%;background:#fff;transition:transform .15s}.insar-toggle.on{background:var(--insar-teal)}.insar-toggle.on i{transform:translateX(17px)}.insar-swipe-state{margin-top:9px;padding:7px;border-radius:6px;text-align:center;color:var(--insar-dark);background:var(--insar-soft);font-size:9px;font-weight:700}
  @media(max-width:390px){.insar-grid{grid-template-columns:1fr}.insar-kpis{grid-template-columns:1fr 1fr}.insar-kpi:last-child{grid-column:1/-1}}
`
